service: graphql-server-demo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-north-1
  deploymentBucket: 
    name: deployment-bucket-stockholm
  environment:
    snsArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.eventDispatchTopic}" ] ]  }
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: 'arn:aws:execute-api:*:*:*/development/POST/@connections/*'


custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  eventDispatchTopic: "${self:service}-event-dispatch-${self:custom.stage}"

functions:
  mainHandler:
    handler: dist/index.handler
    events:
      - sns: ${self:custom.eventDispatchTopic}
      - websocket: 
         route: $connect
      - websocket: 
         route: $disconnect
      - websocket: $default
