service: graphql-server-demo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-north-1
  deploymentBucket: 
    name: deployment-bucket-stockholm

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: 'arn:aws:execute-api:*:*:*/development/POST/@connections/*'

functions:
  mainHandler:
    handler: dist/index.handler
    events:
      - sns: newevent
      - websocket: 
         route: $connect
      - websocket: 
         route: $disconnect
      - websocket: $default
